export const ROLES = {
  ADMIN: 'ADMIN',
  CITIZEN: 'CITIZEN',
  TRAFFIC_OFFICER: 'TRAFFIC_OFFICER',
  REVIEW_OFFICER: 'REVIEW_OFFICER',
}

export const TICKET_STATUS = [
  'ISSUED',
  'PENDING_PAYMENT',
  'PAID',
  'OVERDUE',
  'DISPUTED',
  'CANCELLED'
]

export const PAYMENT_STATUS = ['INITIATED', 'SUCCESS', 'FAILED']

export const DISPUTE_STATUS = ['OPEN', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CLOSED']
